services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    platform: linux/arm64
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gem-cache:/usr/local/bundle
      - node-modules:/myapp/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:password@db:3306

volumes:
  mysql-data:
  gem-cache:
  node-modules:
